ionic-team/ionic-cli

lib/ionic.js, lib/ionic/serve.js
This adds `ionic serve --address XYZ` to `ionic serve`.
When you `ionic serve`, you potentially get a prompt asking you which address to use, making it unsuitable for scripting (e.g. when inside a vagrant provisionier, or just a convenience script to prepare your coding session).
With `--address`, you now get a specific address, e.g. `ionic serve --address localhost --port 6543`, xor a program failure.
=> add option to serve on specific address

lib/ionic.js
`npm update` can be problematic. 
It never works as intended.
Our `npm update` warning should be changed to `npm install`
=> Change update to install

README.md
Inform users who don't want to (because you probably shouldn't) use `sudo` to install node modules globally how to update their file permissions.
=> Suggest changing file permissions on OSX

lib/ionic/serve.js
postToLiveReload was assuming that the server was running localhost, this allows it to run on an IP based address
=> Fix for livereload on IP based addresses

lib/ionic/browser.js
Removing 'cordova-plugin-crosswalk-webview' from plugins when running 'ionic browser revert android' as plugin is crosswalk resource and so should no longer remain after reverting to Android browser - presence of this plugin caused failure of subsequent attempts to run 'ionic platform add android' after removal of Android platform from project.
=> Remove cordova-plugin-crosswalk-webview from plugins on crosswalk revert

lib/ionic/start.js
Fix these warnings
running cordova plugin add org.apache.cordova.device
WARNING: org.apache.cordova.device has been renamed to cordova-plugin-device. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.device` and `cordova plugin add cordova-plugin-device`.
...
running cordova plugin add org.apache.cordova.console
WARNING: org.apache.cordova.console has been renamed to cordova-plugin-console. You may not be getting the latest version! We suggest you `cordova plugin rm org.apache.cordova.console` and `cordova plugin add cordova-plugin-console`.
and add the `cordova-plugin-whitelist` otherwise http requests won't work.
=> Update default plugins for Cordova 5.0.0

lib/ionic/resources/settings.js
Dimensions for ldpi splash screen on small screen android are incorrect and cause a distorted image on these devices.
See http://developer.android.com/guide/practices/screens_support.html#screens-table for correct ldpi resolution
=> Correct ldpi setting for splash screen

lib/hooks/after_platform_add/010_install_plugins.js
`sys` module was deprecated long ago.
There is an ongoing discussion on removing `sys` module completely in the next major version: https://github.com/nodejs/node/pull/2405.
=> Require `util` module instead of the deprecated `sys` module in `010_install_plugins.js`.

lib/hooks/after_prepare/010_add_platform_class.js
fs.readFileSync and fs.writeFileSync encoding options passed with an object
There was a bug in non-latin characters that will convert them to html entities
=> encoding options

lib/ionic/add.js
Stating that the package couldn't be found on any bower error is confusing when things like version conflicts occur (This happens a _lot_ with bower, especially when adding the `ionic-platform-web-client`).
Ideally, we should make bower a dependency of the cli, and not be installing via `exec('some-command-here')`, but this should at least provide a bit better info.
=> Update bower error msg

lib/ionic/generate.js, lib/tasks/cliTasks.js
This adds support to pass a --ts argument to `ionic g` to generate typescript code instead of ES6.
Supported by driftyco/ionic#6008
=> Support for Typescript Generators

README.md
It took a lot of searching through issues to find out how to migrate from the 1.x to 2.0 CLI, hopefully this should make things easier for other people doing the same 😄
=> docs(readme): update docs to reflect CLI 2.0

lib/cli.js, lib/utils/help.js, spec/utils/templates.spec.js
=> fix(cli): npm install under windows

lib/ionic/login.js
Currently when we used `ionic help`, the login command is not listed.  (see this thread : https://forum.ionicframework.com/t/getting-a-session-expired-401-error-in-ionic-cli-for-ionic-upload-command/61749/4 )
This PR adds 'summary' and 'options' for the login command.
=> Add summary and options in settings of login

packages/cli-plugin-ionic-angular/src/generate.ts, packages/cli-plugin-ionic-angular/src/utils/__tests__/generate.ts, packages/cli-plugin-ionic-angular/src/utils/generate.ts
We currently do not want generators to be set up for lazy loading by default. With no lazy loading the user should not be prompted about where they would like their `<insert component type here>` put as it should always go in the "root" ngModule.
=> fix(generators): do not do lazy load by default

packages/cli-plugin-cordova/src/commands/emulate.ts
Server settings ipAddress undefined in emulate command, changed to be same as run command.
=> Fix live reload on emulator - change emulate ipAddress to publicIp

README.md
Ionic 2 Tutorial template currently links to https://github.com/driftyco/ionis2-starter-tutorial and not https://github.com/driftyco/ionic2-starter-tutorial (notice the **s** and not **c** on ionic) causing a 404 on
=> Fix ReadMe Link to Ionic Template

README.md
I further prioritized the current version instructions in the README by removing the "v2" with "current version" and moving the v1 stuff to the back.
=> Further prioritize current version in README

README.md
Makes the npm installer install the stable build instead of being on the @latest branch
=> fix(readme): remove extra @latest in npm install

packages/cli-plugin-ionic1/src/serve/config.ts, packages/cli-plugin-ionic1/src/serve/index.ts
For compatibility with the CLI, which expects this property.
Addresses https://github.com/driftyco/ionic-cli/issues/2274.
=> add httpPort to ionic1 plugin options

packages/cli-utils/src/lib/deploy.ts, packages/ionic/src/commands/upload.ts, packages/ionic/src/lib/upload.ts
Added options to set snapshot metadata for ionic deploy.
Example usage:
`ionic upload --metadata='{"livereload":true, "version":".170625"}' --note="test metadata" `
Fixes:
https://github.com/ionic-team/ionic-cli/issues/2403, https://github.com/ionic-team/ionic-cli/issues/660, https://github.com/ionic-team/ionic-plugin-deploy/issues/95
=> feat(cloud): add options for snapshot metadata

packages/cli-plugin-ionic1/lab/static/js/lab.js
this little pull request makes the labs (-lab) environment pass all params put on the url to the iframes that run the iphone/android and windows ionic.
this way you can pass ionic params to your app also when running in lab mode.
fix for https://github.com/ionic-team/ionic-cli/issues/2431
=> patch for passing params from lab to iframes

README.md
Using example.org as intended in documentation.
Added port as I assume most proxies will use one.
=> docs(readme): change example proxy

README.md
CLI adds "type" attribute, "email" isn't normally present.
=> docs(readme): make service proxy json more real

README.md
with :sparkling_heart: because it is rendered properly on Windows as well.
:heart: is sometimes quite strange, see diff:
=> docs(readme): replace :heart:

packages/cli-plugin-ionic-angular/package.json, packages/cli-plugin-ionic-angular/src/generate.ts, packages/cli-plugin-ionic-angular/src/utils/generate.ts, packages/ionic/src/commands/generate.ts
Adds `module` and `no-module` flags to the CLI
Requires https://github.com/ionic-team/ionic-app-scripts/pull/1141 to be merged first
=> feat(generators): add module options

packages/cli-scripts/docs.js
fixes the problem that each command link first has to redirected to the version with trailing slash
closes https://github.com/ionic-team/ionic-site/issues/1227
=> docs(index): add trailing slash to command links

packages/@ionic/cli-utils/src/commands/build.ts, packages/ionic/src/index.ts
`cordova prepare` is called without the `platform` argument, breaking
platform specific builds.
=> fix cordova "build after hook"

packages/ionic/src/commands/cordova/base.ts
Skipping the build would also be useful for `ionic cordova run` and `ionic cordova emulate`. 
This tries to add this, hope I got everything.
fixes #2915
=> feat(cordova): --no-build for `ionic cordova run|emulate`

package.json, packages/@ionic/cli-framework/package.json, packages/@ionic/cli-plugin-proxy/package.json, packages/@ionic/cli-scripts/package.json, packages/@ionic/cli-utils/package.json, packages/@ionic/discover/package.json, packages/@ionic/lab/package.json, packages/@ionic/schematics-angular/package.json, packages/@ionic/v1-util/package.json
Fix is for Issue #2967 
-- Replaced all 'rm -rf' with rimraf
-- Replaced single quote in lerna exec npm script with double quote to make Windows happy
=> Minor changes to make npm commands run on Windows -- Issue #2967

packages/@ionic/cli-utils/src/lib/project/angular/angular-devkit.ts
This is https://github.com/ionic-team/ionic-cli/pull/3027 's bug fix.
resolve( https://github.com/ionic-team/ionic-cli/blob/master/packages/%40ionic/cli-framework/src/utils/npm.ts#L72 ) needs `package.json` in case path is folder.
So specify index.js.
=> fix(generate): use local @angular-devkit/schematics/tools

packages/@ionic/schematics-angular/page/schema.json
generate page(Angular CLI collection) is check schema.json (not check project .angular-cli.json)
so I think cli should change styleext default.
=> change default styleext scss

packages/@ionic/cli-utils/src/lib/project/angular/index.ts
instead of https://github.com/ionic-team/starters/pull/62.
I think @ionic/schematics-angular should be checked for the latest version.
I hope this method will stay here( https://github.com/ionic-team/ionic-cli/blob/master/packages/%40ionic/cli-utils/src/lib/project/angular/ailments.ts#L10-L16 )
=> CLI check @ionic/schematics-angular version 

packages/@ionic/schematics-angular/page/index.ts, packages/@ionic/schematics-angular/utils/angular/ast-utils.ts
When using NavController in no LazyLoading, target Page must be registered ngModule entryComponents.
I add function `ionic generate page` add ngModule entryComponents.
=> when generate page, add page entryComponents

packages/@ionic/cli-utils/src/lib/project/angular/index.ts
> @ionic/core won't be in the list of dependencies for starters in the stable release
I left it as pull request, so as not to forget it.
=> WIP: feat(cli-utils) remove @ionic/core from cli version check.

packages/@ionic/cli-utils/src/lib/project/angular/serve.ts
This removes the `progress` flag from the CLI arguments in an Angular v6 project.
=> fix(serve): remove progress cli flag

packages/@ionic/schematics-angular/page/files/__name@kebabCase@if-flat__/__name@kebabCase__.page.html
When generating a new page for an Ionic 4 project, the following error is generated:
```
compiler.js:215 Uncaught Error: Template parse errors:
'ion-page' is not a known element:
1. If 'ion-page' is an Angular component, then verify that it is part of this module.
2. If 'ion-page' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<ion-page>
<ion-header>
<ion-toolbar>
```
I believe this will fix that and make the page consistent with the pages generated by the starters.
=> fix(page-schematics): remove ion-page

packages/@ionic/cli-utils/src/lib/project/angular/generate.ts, packages/ionic/src/commands/generate.ts
There is a disparity between our starters and `ionic generate`. Our generators do not _force_ the `pages/` & `components/` prefix to the name, but all our starters have pages within a `pages/` folder, so when `ionic generate` is used for the first time, it generates a page outside the `pages/` folder, which is weird.
These updates suppress our (previously) heavy recommendation of prefixing pages with `pages/`, and opens it up to users' preferences, as Angular has no strong opinions on this, either.
See the updates in our starters here: https://github.com/ionic-team/starters/pull/341
cc @mlynch
=> Generator Updates

packages/@ionic/cli-utils/src/lib/project/angular/serve.ts, packages/@ionic/cli-utils/src/lib/project/ionic-angular/serve.ts, packages/@ionic/cli-utils/src/lib/project/ionic1/serve.ts
Fixes https://github.com/ionic-team/ionic-cli/issues/3410
Change `await isHostConnectable('localhost', port);` to `await isHostConnectable(options.address, port);` .  I think this is consistent `findOpenIonicPorts()`'s address.
---
- cause of my error
'localhost' can't resolve ip-address.
reference: https://github.com/nodejs/node/issues/2237#issuecomment-124718020
- cause of https://github.com/ionic-team/ionic-cli/issues/3410#issuecomment-408444428
change address `192.168.254.58`, but connect check by `localhost`.
=> fix(cli-utils/project): pass the host address as it is

packages/@ionic/cli-framework/src/utils/network.ts
if check host connection, not use 0.0.0.0. Maybe DevApp not use this method.
Fix: https://github.com/ionic-team/ionic-cli/issues/3473
=> fix(cli-framework/network): change 0.0.0.0 to 127.0.0.1

packages/@ionic/cli-framework/package.json, packages/@ionic/cli-framework/src/utils/process.ts, packages/@ionic/cli-utils/src/lib/serve.ts, packages/@ionic/cli-utils/src/lib/shell.ts, packages/ionic/src/commands/cordova/run.ts, packages/ionic/src/commands/serve.ts
Fixes https://github.com/ionic-team/ionic-cli/issues/3401
=> WIP: Fix #3401

packages/ionic/src/lib/serve.ts
These are highly unlikely to be connectable externally
=> feat(serve): ignore external link-local addresses

packages/@ionic/lab/src/stencil/components/ionlab-device-frame/ionlab-device-frame.css, packages/@ionic/lab/src/stencil/components/ionlab-preview/ionlab-preview.tsx
fixes android and windows statusbar so it is on top of the header in lab
references #3069 
before:
aftah:
=> fix(lab): remove css that places the statusbar above the header

packages/@ionic/cli-framework/package.json, packages/@ionic/cli-framework/tslint.js, packages/@ionic/cli-framework/tslint.json, packages/@ionic/discover/package.json, packages/@ionic/discover/tslint.js, packages/@ionic/discover/tslint.json, packages/@ionic/lab/package.json, packages/@ionic/lab/tslint.js, packages/@ionic/lab/tslint.json, packages/@ionic/utils-fs/package.json, packages/@ionic/utils-fs/tslint.js, packages/@ionic/utils-fs/tslint.json, packages/@ionic/utils-network/package.json, packages/@ionic/utils-network/tslint.js, packages/@ionic/utils-network/tslint.json, packages/@ionic/v1-toolkit/package.json, packages/@ionic/v1-toolkit/tslint.js, packages/@ionic/v1-toolkit/tslint.json, packages/cli-scripts/package.json, packages/cli-scripts/tslint.js, packages/cli-scripts/tslint.json, packages/ionic/package.json, packages/ionic/tslint.js, packages/ionic/tslint.json, tslint.base.js, tslint.base.json
Visual Studio Code and WebStorm currently don't support the [undocumented][1]
tslint.js configuration format for TSLint.
[1]: https://palantir.github.io/tslint/usage/configuration/
=> chore(lint): replace tslint.js with tslint.json

packages/ionic/src/lib/executor.ts
This fixes #3797 -- if you included Ionic CLI options *before* `cordova`, it would do the command positional parsing including those options since they aren't properly parsed out of the options sent to cordova even though they've already been consumed by Ionic.
This was handled by removing all arguments up to the final command in the command path -- the implication is that all arguments / options that follow the command in the path are for use by the command.
=> fix(cli): Exclude options for command argument parsing (#3797)

packages/ionic/src/lib/doctor/ailments/index.ts
Regex doesn't match on a multiline meta tag, an strict matcher is proposed to prevent match on other meta tags, only should match if a meta tag has name="viewport" property
done in test bench: https://regex101.com/r/yy1zT2/1
=> fix(): ionic doctor ViewportFixNotSet Ailment

packages/@ionic/v1-toolkit/src/lib/serve.ts
This is the change I'd make for #3856. We've tested this change and it works for the scenario described, as compared to ionic@4.10.2 where .tpl.html requests fail.
=> v1-toolkit now sends Access-Control-Allow-Origin: *

packages/ionic/src/lib/integrations/capacitor/index.ts
On Capacitor beta 22, it added support for yarn package manager.
If it detects yarn installed and no `--npm-client` param is passed, it will prompt the user to choose a package manager, but that blocks the ionic cli. (see https://github.com/ionic-team/capacitor/issues/1453)
This PR will pass the `--npm-client` param to Capacitor CLI based on the configured `npmClient`
=> fix(capacitor): Send --npm-client param to capacitor init

packages/ionic/src/commands/cordova/base.ts, packages/ionic/src/lib/integrations/cordova/index.ts
Prevents users from adding Cordova to vue and react projects.
Prevents it for `ionic integrations enable cordova` and ` ionic cordova platform add`, not sure if more commands need it too.
=> fix(react/vue): prevent usage of Cordova on vue and react projects

packages/@ionic/cli-framework/package.json, packages/ionic/package.json
As node 8.9.4 or greater is required, update the engines in the package.json files that had an older value.
=> chore: update node engines to >=8.9.4

packages/ionic/CHANGELOG.md
It's noted explicitly in the breaking changes section but was left vague further up.
=> docs(changelog): clarify exact min node ver req

packages/ionic/CHANGELOG.md
When upgrading Angular 7 projects use `npm i @ionic/angular-toolkit@1.5.1` otherwise it installs v2.0+ which is for Angular 8 and results in errors like this:
```[INFO] Hardware device(s) found for android. Using --device.
> ng.cmd run app:ionic-cordova-build --platform=android
Schema validation failed with the following errors:
Data path ".builders['cordova-build']" should have required property 'class'.
[ERROR] An error occurred while running subprocess ng.
```
Based on the [solution presented here](https://github.com/ionic-team/angular-toolkit/issues/166#issuecomment-510460934).
=> docs(changelog): angular-toolkit upgrade clarification

packages/ionic/src/commands/cordova/run.ts
Some additional updates related to #4156 to ensure that stdio is properly set for 'runServeDeploy()' and 'runBuildDeploy()' so that `ionic cordova run` functions as expected in all code paths, specifically with various combinations of `--livereload`, `--verbose`, and `--no-native-run`.
fixes https://github.com/ionic-team/ionic-cli/issues/4165
=> Additional #4156 work

packages/@ionic/cli/src/commands/capacitor/run.ts, packages/@ionic/cli/src/commands/cordova/run.ts, packages/@ionic/cli/src/definitions.ts, packages/@ionic/cli/src/lib/__tests__/serve.ts, packages/@ionic/cli/src/lib/project/angular/__tests__/serve.ts, packages/@ionic/cli/src/lib/project/angular/serve.ts, packages/@ionic/cli/src/lib/project/ionic-angular/__tests__/serve.ts, packages/@ionic/cli/src/lib/project/ionic1/__tests__/serve.ts, packages/@ionic/cli/src/lib/serve.ts
This adds a `--public-host` option to `ionic serve`. It differs slighty
from the Angular CLI's `--public-host` option in that the Ionic CLI will
open the provided host, instead of localhost.
Please test: `npm i -g @ionic/cli@6.2.0-testing.5`
resolves https://github.com/ionic-team/ionic-cli/issues/3558
=> feat(serve): add `--public-host` option

packages/@ionic/cli/src/lib/project/angular/__tests__/generate.ts, packages/@ionic/cli/src/lib/project/angular/__tests__/serve.ts, packages/@ionic/cli/src/lib/project/angular/build.ts, packages/@ionic/cli/src/lib/project/angular/generate.ts, packages/@ionic/cli/src/lib/project/angular/serve.ts
This MR ports some changes from #4311, which is no longer required after the `--multi-app` feature was introduced.
With this MR, the Angular specific Runner commands will consistently provide all defaults passed to the Angular CLI in the `createOptionsFromCommandLine` method.
Closes #4192
=> fix(angular): always provide the project name fallback

packages/@ionic/cli/src/lib/project/index.ts
This adds support for Ionic 5's dark mode theme colors in the Wizard, and computes plausible dark-mode alternatives for a given theme color.
=> Support dark and light mode themes

packages/@ionic/cli/src/commands/package/build.ts
Added support for triggering builds that will ship the artifact to an App Store.
=> Added functionality to deploy to app store from the CLI

packages/@ionic/cli/src/commands/start.ts, packages/@ionic/cli/src/definitions.ts, packages/@ionic/cli/src/lib/project/index.ts, packages/@ionic/cli/src/lib/start.ts
This adds support for fetching and storing an app icon and splash from the App Wizard. Also adds support to force capacitor to default Y.
=> Wizard resources

packages/@ionic/cli/src/commands/capacitor/build.ts, packages/@ionic/cli/src/commands/capacitor/run.ts
Added the option `--no-open` Do not invoke Capacitor open, to the ionic capacitor `build` and `run` commands.
This option will make it easier to use ionic capacitor from the command line, especially when you what to use the `--livereload` option.
Currently, if you what to use live reload from the CLI. You can not use the `ionic capacitor run <platform> --livereload` command, because it will always start the corresponding IDE. So you have to write custom scripts that will update the `capacitor.config.json` file with the correct information needed for live reload to work. This pull request can make this use case simpler.
=> Added the --no-open option

packages/@ionic/cli/src/commands/capacitor/run.ts
Adds context to the help/docs to explain how to use when serving to emulators and devices with live reload server. By default the docs didn't explain that the live reload server opens at localhost and this doesn't work when using emulators/devices. 
For example, android can only reach the host machine through LAN IP or host loopback address 10.0.2.2. Localhost points to the device itself and the web view displays an error (unreachable host).
Future work planned to streamline how this works e.g. for Android using the 10.0.2.2 default host address: (https://github.com/ionic-team/ionic-cli/issues/4419)
=> Added note to explain how to use for serving to emulators and to lan/devices

packages/@ionic/cli/src/commands/package/deploy.ts
Fixed the name of the command for `ionic package deploy`
=> fix(package): Fixed name of the package deploy name

packages/@ionic/cli/src/definitions.ts, packages/@ionic/cli/src/guards.ts, packages/@ionic/cli/src/lib/integrations/cordova/__tests__/project.ts, packages/@ionic/cli/src/lib/integrations/cordova/project.ts
fixes https://github.com/ionic-team/ionic-cli/issues/4467
=> fix(cordova): handle new format of output.json files for Android builds
