ionic-team/ionic-cli

lib/ionic.js, lib/ionic/cordova.js
Pull request for https://github.com/driftyco/ionic-cli/issues/315
=> Resolves #315 - Add a no hook option for Cordova commands

lib/ionic/docs.js
=> feat(docs): make it suggest the closest result to user's input

lib/ionic.js, lib/ionic/ionitron.js
Now, Ionitron is multi-language.
Added translation to Spanish.
**Use:** ionic --ionitron [--lang] 
> ionic --ionitron --es
=> Ionitron multi-language - Translated to Spanish

lib/tasks/cliTasks.js
=> Added help text for push

lib/cli.js
=> Fixed spelling mistake of error output in 3 places

lib/ionic/start.js
Depends on https://github.com/driftyco/ionic-app-lib/pull/38
=> Feat(start): dynamically load v2 or v1 start task from app lib

lib/ionic/cordova.js, lib/tasks/cliTasks.js, spec/cli.spec.js
=> [issue #605] accept --address option for emulate command

lib/ionic/cordova.js, lib/tasks/cliTasks.js
Create alias plugins to plugin. :) 
https://twitter.com/ionicframework/status/682729562762031104
=> Plugins alias

.gitignore, appveyor.yml, circle.yml, package.json
This pull request will add a few testing features around cirleci integration. This includes:
- Istanbul and Coveralls integration
- CircleCI testing on multiple supported versions of Nodejs
=> Add testing process

lib/ionic/share.js
=> fix(share): use app-lib project utility

ionic.config.json, lib/ionic/build.js, lib/ionic/emulate.js, lib/ionic/run.js, lib/ionic/serve.js, lib/utils/npmScripts.js, spec/tasks/build.spec.js, spec/tasks/emulate.spec.js, spec/tasks/run.spec.js, spec/tasks/serve.spec.js
Add interface so that build and serve tasks can be done entirely within app-scripts using package.json script commands.
=> New app scripts interface

lib/ionic/generate.js
=> docs(generator): add docs help in usage #1411

packages/ionic/src/commands/start.ts, packages/ionic/src/lib/start.ts, packages/ionic/src/lib/starter-templates.ts
Allows starter dependency patching + enforces app-base is available for Ionic 2 starters apply.
=> V3 package json

README.md
Merge it with the next release
=> docs(readme): add super template

CONTRIBUTING.md
Instructions to windows users setup a local dev environment so them can contribute to CLI project.
Discussion: #2225
=> chore(contributing): explain windows local dev setup

packages/ionic/src/commands/generate.ts
I added new check for empty names.
=> Added check to verify if name is empty at generate.

README.md, packages/cli-plugin-cordova/src/commands/resources.ts, packages/cli-plugin-cordova/src/lib/__tests__/resources.ts, packages/cli-plugin-cordova/src/lib/resources.ts, packages/cli-utils/src/definitions.ts, packages/cli-utils/src/lib/config.ts, packages/ionic/src/commands/start.ts, packages/ionic/src/lib/start.ts
=> feature(config): --timeout / --no-timeout flags

README.md
https://ecotrust-canada.github.io/markdown-toc/
=> docs(readme): Table of Contents

README.md
added relationship to all livereload commands, not only `ionic serve`
added note about usage in app code
added note about required restart of command
=> docs(readme): More information about Service Proxies

packages/ionic/src/commands/cordova/resources.ts
outcommented variable is not present anywhere, comment is also wrong, so no need to keep it around
=> chore(resources): remove outdated comment

packages/@ionic/cli-utils/src/lib/project/angular/app-scripts.ts, packages/@ionic/cli-utils/src/lib/project/angular/generate.ts
Change define two functions.
https://github.com/ionic-team/ionic-cli/pull/3024/files/34466b25a0ef8b5802495de2fe96f00406897d85#diff-3046d014b39b25dfe813bf43052acb19
I'm sorry I could only do source reading because I can't build it. Thanks for instruct.
=> import local @angular-devkit/schematics

packages/@ionic/schematics-angular/page/files/__path__/__name@kebabCase@if-flat__/__name@kebabCase__.page.ts
1. selector match https://github.com/ionic-team/starters/blob/master/angular/official/blank/src/app/pages/home/home.page.ts 
fix https://github.com/ionic-team/ionic-cli/issues/3019#issuecomment-375599108
2. default routing NavController is include
=> change generate template

packages/@ionic/cli-utils/src/lib/project/angular/ailments.ts
I made common version check method, and add version check package.
package: ionic/core, ionic/schematics-angular, angular/cli, angular-devkit/core, angular-devkit/schematics
=> feat(ailments): add version check package

packages/@ionic/cli-utils/src/definitions.ts, packages/@ionic/cli-utils/src/lib/integrations/capacitor/index.ts, packages/@ionic/cli-utils/src/lib/shell.ts, packages/ionic/src/commands/start.ts
Fixes https://github.com/ionic-team/ionic-cli/issues/3391
=> Fix `Command not found: capacitor` error with `ionic start --capacitor`

packages/@ionic/schematics-angular/page/files/__name@dasherize@if-flat__/__name@dasherize__.page.ts, packages/@ionic/schematics-angular/page/index.ts, packages/@ionic/schematics-angular/page/schema.json
Fixes https://github.com/ionic-team/ionic-cli/issues/3389
=> Generate proper page selector

packages/@ionic/cli-utils/src/definitions.ts, packages/@ionic/cli-utils/src/lib/integrations/cordova/resources.ts, packages/ionic/src/commands/cordova/resources.ts
This will fix the "hanging" issue explained in https://github.com/ionic-team/ionic-cli/issues/3398 by introducing another step, which is always piping the response to a temporary file and collecting image transform results before copying the transformed images to the project.
Fixes https://github.com/ionic-team/ionic-cli/issues/3398
Fixes https://github.com/ionic-team/ionic-cli/issues/3385
=> fix(resources): fix hanging issue while transforming images

packages/@ionic/ng-toolkit/src/cordova-serve/index.ts, packages/@ionic/ng-toolkit/src/cordova-serve/schema.d.ts, packages/@ionic/ng-toolkit/src/cordova-serve/schema.json
You forgot about proxyConfig, which totally indispensable for development.
=> Added forgotten proxyConfig property

packages/@ionic/cli-framework/src/definitions.ts, packages/@ionic/cli-framework/src/guards.ts, packages/@ionic/cli-framework/src/lib/__tests__/prompts.ts, packages/@ionic/cli-framework/src/lib/index.ts, packages/@ionic/cli-framework/src/lib/output.ts, packages/@ionic/cli-framework/src/lib/prompts.ts, packages/@ionic/cli-framework/src/lib/tasks.ts, packages/@ionic/cli-utils/src/definitions.ts, packages/@ionic/cli-utils/src/index.ts, packages/@ionic/cli-utils/src/lib/command.ts, packages/@ionic/cli-utils/src/lib/environment.ts, packages/@ionic/cli-utils/src/lib/integrations/capacitor/index.ts, packages/@ionic/cli-utils/src/lib/integrations/cordova/index.ts, packages/@ionic/cli-utils/src/lib/integrations/index.ts, packages/@ionic/cli-utils/src/lib/project/index.ts, packages/@ionic/cli-utils/src/lib/prompts.ts, packages/@ionic/cli-utils/src/lib/serve.ts, packages/cli-scripts/src/docs/index.ts, packages/ionic/src/commands/capacitor/base.ts, packages/ionic/src/commands/cordova/base.ts, packages/ionic/src/commands/cordova/platform.ts, packages/ionic/src/commands/cordova/resources.ts, packages/ionic/src/commands/doctor/base.ts, packages/ionic/src/commands/info.ts, packages/ionic/src/commands/link.ts, packages/ionic/src/commands/monitoring/syncmaps.ts, packages/ionic/src/commands/ssh/generate.ts, packages/ionic/src/commands/start.ts, packages/ionic/src/index.ts
Keeping BottomBar open seems to be a consistent issue on Windows. BottomBar creates a readline interface, so SIGINT has to go through it, and the signal doesn't seem to bubble up properly, which means the Ionic CLI cannot properly clean up resources during a Ctrl-C, leading to serve issues where the underlying CLI is not terminated.
Fixes https://github.com/ionic-team/ionic-cli/issues/3401 (again)
Fixes https://github.com/ionic-team/ionic-cli/issues/3497
=> re-architect tasks

packages/@ionic/ng-toolkit/src/cordova-build/schema.d.ts, packages/@ionic/ng-toolkit/src/cordova-build/schema.json, packages/@ionic/ng-toolkit/src/cordova-serve/schema.d.ts, packages/@ionic/ng-toolkit/src/cordova-serve/schema.json
@dwieeb ng-toolkit change kebab-case to camel-case. So set kebab-case option.
It may work. But I don't understand how to test ng-toolkit. Please tell me how to install develop ng-toolkit in local v4 project.
( * this week, I can't develop more. If you'd like, please test it )
Resolves https://github.com/ionic-team/ionic-cli/issues/3515
=> be able to use --source-map flag in cordova.

packages/ionic/src/commands/start.ts
WIP: DO NOT MERGE
PR for making v4 the default
=> feat(): make v4 default

packages/ionic/src/constants.ts, packages/ionic/src/lib/project/index.ts
Change be able to valid project type react (and vue).
related: https://github.com/ionic-team/ionic-cli/pull/3936
=> fix(react/vue): add project type at creat project.

packages/ionic/src/commands/start.ts, packages/ionic/src/definitions.ts, packages/ionic/src/lib/start.ts
Add @dotNetkow starter template as well as Conference app starter template to Ionic Angular 4.
=> Modify the ionic start templates available

packages/ionic/src/commands/start.ts
Change check project-type and support `ionic start myApp conference --type=react` .
related https://github.com/ionic-team/ionic-react-conference-app/pull/16
=> fix(react): support react git repo

packages/ionic/src/lib/integrations/capacitor/index.ts
This PR is to correct the capacitor configuration for create react app.
=> fix(react): correct the web-dir path for react and capacitor

packages/ionic/src/commands/cordova/platform.ts, packages/ionic/src/commands/cordova/plugin.ts
=> fix(cordova): don't append --save to plugin commands

packages/ionic/src/lib/open.ts, packages/ionic/src/lib/sso.ts
Fixes https://github.com/ionic-team/ionic-cli/issues/4208.
=> fix(login): don't doubly encode SSO login URL params

packages/ionic/src/lib/project/react/build.ts, packages/ionic/src/lib/project/react/serve.ts
Remove beta flag from cli help command.
Now in react project:
```
$ ionic cap -h
```
=> remove(beta): React changed stable .

packages/ionic/src/commands/capacitor/add.ts, packages/ionic/src/commands/capacitor/copy.ts, packages/ionic/src/commands/capacitor/index.ts, packages/ionic/src/commands/capacitor/open.ts, packages/ionic/src/commands/capacitor/sync.ts, packages/ionic/src/commands/capacitor/update.ts
Remove beta flag from cli help command.
Now:
```
$ ionic cap -h
```
=> remove(beta): Capacitor changed stable .

packages/@ionic/cli/src/lib/start.ts
Closes https://github.com/ionic-team/ionic-cli/issues/4306
=> Update "my-first-app" starter template to new Capacitor version

packages/@ionic/cli/src/lib/start.ts
Removes the Studio advert until we can replace it with something more appropriate
=> chore(): Remove studio advert

packages/@ionic/cli/src/definitions.ts, packages/@ionic/cli/src/lib/utils/__tests__/npm.ts, packages/@ionic/cli/src/lib/utils/npm.ts
This PR adds support for the package manager `pnpm`.
More info about `pnpm `: https://pnpm.js.org/en/
Closes: #4285
=> feat: add support for pnpm

packages/@ionic/cli/src/commands/start.ts, packages/@ionic/cli/src/lib/session.ts
This adds a signup prompt to the start experience.
=> Add signup prompt to start

packages/@ionic/cli/src/commands/start.ts, packages/@ionic/cli/src/definitions.ts, packages/@ionic/cli/src/lib/project/angular/index.ts, packages/@ionic/cli/src/lib/project/index.ts, packages/@ionic/cli/src/lib/project/react/index.ts, packages/@ionic/cli/src/lib/start.ts, packages/@ionic/cli/src/lib/utils/color.ts
This pulls down the app created on the website, initializes all the values for the app start, updates a theme file w/ a theme color, and writes it back.
Currently looking for a review in terms of whether I've put the functionality in the right place or anything else that I should fix. 
Also I'll be fixing the `START_WIZARD_URL` env var later
=> Start wizard

packages/@ionic/cli/src/commands/start.ts
Adds a check for the destination dir before continuing
=> Check directory before writing

packages/@ionic/cli/src/commands/start.ts
Adds better error detection and logging for the wizard
=> Wizard error logging

packages/@ionic/cli/src/definitions.ts, packages/@ionic/cli/src/guards.ts, packages/@ionic/cli/src/lib/integrations/cordova/project.ts
fixes https://github.com/ionic-team/ionic-cli/issues/4374
=> fix(cordova): use output.json to deploy correct apk
